Abba-Zone/eabbashop_web

- frontened/src/Handler/ErrorHandler.tsx
- frontened/src/Handler/TokenHandler.ts
- frontened/src/Service/member.ts
- frontened/src/api/MainApi.ts
- frontened/src/api/MemberApi.ts
- frontened/src/pages/Login.tsx
- frontened/src/types/address.d.ts
- frontened/src/types/member.d.ts
- frontened/src/types/response.d.ts
Develop MemberAPI
- 일반로그인
- 회원가입
- 이메일인증
- 전화번호인증
- 역할수정
- 로그아웃
- 회원리스트조회
- 회원정보조회
- 회원정보수정
- 비밀번호변경
- 회원탈퇴
> 🚀: Add draft MemberAPI

- frontened/src/constants/names.tsx
- frontened/src/pages/Signup.tsx
add contants directory on /src/constants and make 'names.tsx' for manage string on our projects.
it has 3 object as const. 
- menu_names
- page_titles
- money_units
- goods_info
But we have to make it more detailed.
> Setting for dev

- backend/abba/src/main/java/com/zon/abba/members/client/KakaoClient.java
- backend/abba/src/main/java/com/zon/abba/members/controller/OAuthController.java
- backend/abba/src/main/java/com/zon/abba/members/request/KakaoAccessTokenRequest.java
- backend/abba/src/main/java/com/zon/abba/members/response/KakaoAccessTokenResponse.java
- backend/abba/src/main/java/com/zon/abba/members/response/KakaoUserInfoResponse.java
- backend/abba/src/main/java/com/zon/abba/members/service/OAuthService.java
카카오 인가 코드 입력
카카오 access token 발행
카카오 개인 정보 요청
> 🚀 kakao social login clear

- backend/abba/build.gradle
- backend/abba/src/main/java/com/zon/abba/common/code/BasicCode.java
- backend/abba/src/main/java/com/zon/abba/common/code/StatusCode.java
- backend/abba/src/main/java/com/zon/abba/common/config/OpenApiConfig.java
- backend/abba/src/main/java/com/zon/abba/common/config/SecurityConfig.java
- backend/abba/src/main/java/com/zon/abba/common/response/ResponseBody.java
- backend/abba/src/main/java/com/zon/abba/common/security/JwtAuthenticationFilter.java
- backend/abba/src/main/java/com/zon/abba/common/security/JwtTokenProvider.java
- backend/abba/src/main/java/com/zon/abba/members/client/GoogleClient.java
- backend/abba/src/main/java/com/zon/abba/members/client/KakaoClient.java
- backend/abba/src/main/java/com/zon/abba/members/controller/MemberController.java
- backend/abba/src/main/java/com/zon/abba/members/controller/OAuthController.java
- backend/abba/src/main/java/com/zon/abba/members/request/LoginRequest.java
- backend/abba/src/main/java/com/zon/abba/members/response/GoogleUserInfoResponse.java
- backend/abba/src/main/java/com/zon/abba/members/response/LoginResponse.java
- backend/abba/src/main/java/com/zon/abba/members/response/SignupResponse.java
- backend/abba/src/main/java/com/zon/abba/members/service/CustomUserDetailsService.java
- backend/abba/src/main/java/com/zon/abba/members/service/LoginService.java
- backend/abba/src/main/java/com/zon/abba/members/service/OAuthService.java
Spring Security 적용
member login api 간단 작성
swagger 설정
jwt 설정
access token 생성
refresh token 생성 중
> Be feat login

- frontend/Dockerfile
- frontend/nginx.conf
Add Doker Setting Files
Dokerfile
nginx.conf
> 📈: Add Doker Setting Files

- backend/abba/build.gradle
- backend/abba/src/main/java/com/zon/abba/common/config/SecurityConfig.java
- backend/abba/src/main/java/com/zon/abba/common/cors/WebConfig.java
- backend/abba/src/main/java/com/zon/abba/common/exception/ExpiredTokenException.java
- backend/abba/src/main/java/com/zon/abba/common/exception/GlobalExceptionHandler.java
- backend/abba/src/main/java/com/zon/abba/common/exception/LogoutException.java
- backend/abba/src/main/java/com/zon/abba/common/redis/RedisConfig.java
- backend/abba/src/main/java/com/zon/abba/common/redis/RedisService.java
- backend/abba/src/main/java/com/zon/abba/common/response/ResponseBody.java
- backend/abba/src/main/java/com/zon/abba/common/security/JwtAuthenticationFilter.java
- backend/abba/src/main/java/com/zon/abba/common/security/JwtTokenProvider.java
- backend/abba/src/main/java/com/zon/abba/common/security/SecurityConfig.java
- backend/abba/src/main/java/com/zon/abba/common/swagger/OpenApiConfig.java
- backend/abba/src/main/java/com/zon/abba/members/controller/MemberController.java
- backend/abba/src/main/java/com/zon/abba/members/controller/OAuthController.java
- backend/abba/src/main/java/com/zon/abba/members/dto/TokenDto.java
- backend/abba/src/main/java/com/zon/abba/members/entity/Member.java
- backend/abba/src/main/java/com/zon/abba/members/request/SignupRequest.java
- backend/abba/src/main/java/com/zon/abba/members/response/SignupResponse.java
- backend/abba/src/main/java/com/zon/abba/members/service/LoginService.java
- backend/abba/src/main/java/com/zon/abba/members/service/LogoutService.java
- backend/abba/src/main/java/com/zon/abba/members/service/ReissueService.java
- backend/abba/src/main/java/com/zon/abba/members/service/SignupService.java
- 회원가입 로직 구현
- 로그아웃 로직 구현
- 리프레쉬 토큰 재발급 로직 구현
- redis 설정
- 일부 log 수정
> Be feat signup

- frontend/src/apis/memberApi.ts
- frontend/src/components/admin/member/MemberList.tsx
- frontend/src/components/admin/member/MemberListCard.tsx
- frontend/src/components/common/list/BottomButton.tsx
- frontend/src/components/common/list/SearchSet.tsx
- frontend/src/components/index.tsx
- frontend/src/pages/admin/AdminMemberList.tsx
- frontend/src/pages/admin/MemberTest.tsx
- frontend/src/services/member.ts
- frontend/src/types/member.d.ts
- Search Component
- bottom button
- List Card
- Connect Api and Page
https://www.notion.so/chiheonlee/20df00d1e07748ea999f938171a5b036
> Develop Member List

- frontend/src/apis/memberApi.ts
- frontend/src/components/admin/member/MemberListCard.tsx
- frontend/src/components/admin/memberDetail/MemberAdminInfo.tsx
- frontend/src/types/member.d.ts
> 💄STYLE: Change Value Name

- frontend/src/components/admin/paymentRequestList/AdminPaymentRequestListCard.tsx
- frontend/src/components/admin/paymentRequestList/AdminPaymentRequestListComponent.tsx
- frontend/src/components/admin/refundList/AdminRefundCard.tsx
- frontend/src/components/admin/refundList/AdminRefundListComponent.tsx
- frontend/src/components/admin/shareLineList/AdminShareLineListCard.tsx
- frontend/src/components/admin/shareLineList/AdminShareLineListComponent.tsx
- frontend/src/components/admin/shareMoneyDetailList/AdminShareMoneyDetailList.tsx
- frontend/src/components/admin/shareMoneyDetailList/AdminShareMoneyDetailListComponent.tsx
- frontend/src/components/admin/shareMoneyList/AdminShareMoneyListCard.tsx
- frontend/src/components/admin/shareMoneyList/AdminShareMoneyListComponent.tsx
- frontend/src/components/admin/transferCancelList/AdminTransferCancelListCard.tsx
- frontend/src/components/admin/transferCancelList/AdminTransferCancelListComponent.tsx
- frontend/src/components/admin/transferList/AdminTransferListCard.tsx
- frontend/src/components/admin/transferList/AdminTransferListComponent.tsx
- frontend/src/pages/admin/AdminRefundDetail.tsx
- frontend/src/pages/index.tsx
- frontend/src/routes/RoutePath.tsx
- frontend/src/types/request.d.ts
- frontend/src/types/share.d.ts
- Develop Components For ShareLineList
- Develop Components For ShareMoneyList
- Develop Components For ShareMoneyDetailPage
- Develop Components For TransferListPage
- Develop Components For PaymentListPage
- Develop Components For TransferCancelPAge
- Develop Components For RefundListPage
- Add Types For Components Developing Today
- Add RefundDetailPage For RefundListPage
>  Develop List Components

- backend/abba/src/main/java/com/zon/abba/common/swagger/OpenApiConfig.java
swagger server url setting
https:// abbazon.global
http://localhost:8080
> 🚀 adding swagger server uri

- frontend/src/components/common/AdminHaeder.tsx
- frontend/src/components/common/NavBar.tsx
- frontend/src/components/common/ShopHeader.tsx
- frontend/src/components/common/style.css
- frontend/src/lang/en/Common.json
- frontend/src/lang/ko/Common.json
Add shop header and signin signup button on header
> Add shop header and signin signup button on header

- backend/abba/src/main/java/com/zon/abba/member/service/CustomUserDetailsService.java
token 생성시 email로 유저 정보를 찾는 방식을 memberId로 수정
> 🚀 update loadUserByUsername call member by memberId

- frontend/src/apis/memberApi.ts
- frontend/src/components/common/ShopHeader.tsx
- frontend/src/handlers/tokenHandler.ts
- frontend/src/pages/shop/Login.tsx
- frontend/src/pages/shop/Signup.tsx
- frontend/src/services/member.ts
- frontend/src/types/member.d.ts
Change APIs and services on SignUp and Login Page + change header by UserInfo who login
> Change APIs and services on SignUp and Login Page + change header by UserInfo who login

- frontend/src/apis/memberApi.ts
- frontend/src/lang/en/Login.json
- frontend/src/lang/en/SignUp.json
- frontend/src/lang/i18n.ts
- frontend/src/lang/ja/Common.json
- frontend/src/lang/ja/Login.json
- frontend/src/lang/ja/SignUp.json
- frontend/src/lang/ko/Login.json
- frontend/src/lang/ko/SignUp.json
- frontend/src/lang/zh/Common.json
- frontend/src/lang/zh/Login.json
- frontend/src/lang/zh/SignUp.json
- frontend/src/pages/shop/Login.tsx
- frontend/src/pages/shop/Signup.tsx
- frontend/src/services/member.ts
FE_CH10 i18n MultiLanguage work in Login page
make Login.json in 4 languages(ko,en,ja,zh) and make it works
> FE_CH10 i18n MultiLanguage work in Login page

- frontend/src/components/common/AdminHaeder.tsx
- frontend/src/components/common/Header.tsx
- frontend/src/components/common/ShopHeader.tsx
- frontend/src/lang/en/Common.json
- frontend/src/lang/i18n.ts
- frontend/src/lang/ja/Common.json
- frontend/src/lang/ko/Common.json
- frontend/src/lang/zh/Common.json
- frontend/src/pages/shop/Login.tsx
Step 1 . When user choose language make it variable and save on localstorage.
Step 2. i18n us this variable when it has to init.
> [FE_CH11] resolve The Issue i18n sets on kor when refresh website. 

- backend/abba/src/main/java/com/zon/abba/account/repository/PointsHistoryRepository.java
> 🚀 pointshistory error resolution

- frontend/src/apis/board.ts
- frontend/src/apis/file.ts
- frontend/src/apis/productApi.ts
- frontend/src/apis/store.ts
- frontend/src/components/admin/boardDetail/AdminBoardModifyModal.tsx
- frontend/src/components/admin/productDetail/AdminProductInfo.tsx
- frontend/src/components/admin/productDetail/AdminProductModifyModal.tsx
- frontend/src/components/index.tsx
- frontend/src/pages/admin/AdminBoardDetail.tsx
- frontend/src/pages/admin/AdminLetter.tsx
- frontend/src/pages/admin/AdminNotice.tsx
- frontend/src/pages/admin/AdminProductDetail.tsx
- frontend/src/services/board.ts
- frontend/src/services/file.ts
- frontend/src/services/product.ts
- frontend/src/types/board.d.ts
- frontend/src/types/categoty.d.ts
- frontend/src/types/product.d.ts
- Request for S3 deletion when deleting images & videos
- Request to add S3 when registering new images & videos
- When modifying thumnail, request new image registration after deleting S3
- Fix update
- Connect Apis
> 🚀FEAT: Develop Modify Components For Products&Board

- backend/abba/src/main/java/com/zon/abba/upload/controller/UploadController.java
- backend/abba/src/main/java/com/zon/abba/upload/dto/FileUrl.java
- backend/abba/src/main/java/com/zon/abba/upload/request/FileUrlRequest.java
- backend/abba/src/main/java/com/zon/abba/upload/service/S3Service.java
> 🚀 create upload list delete api

- backend/abba/src/main/java/com/zon/abba/board/controller/BoardController.java
- backend/abba/src/main/java/com/zon/abba/board/dto/BoardDto.java
- backend/abba/src/main/java/com/zon/abba/board/entity/Board.java
- backend/abba/src/main/java/com/zon/abba/board/mapping/BoardList.java
- backend/abba/src/main/java/com/zon/abba/board/repository/BoardRepository.java
- backend/abba/src/main/java/com/zon/abba/board/request/BoardIdRequest.java
- backend/abba/src/main/java/com/zon/abba/board/request/DetailBoardRequest.java
- backend/abba/src/main/java/com/zon/abba/board/request/RegisterBoardRequest.java
- backend/abba/src/main/java/com/zon/abba/board/response/DetailBoardResponse.java
- backend/abba/src/main/java/com/zon/abba/board/service/BoardService.java
> 🚀 create board register api

- .gitmodules
> remove submodule backend/abba/config

- frontend/src/apis/memberApi.ts
- frontend/src/components/common/ShopHeader.tsx
- frontend/src/lang/ko/Login.json
- frontend/src/pages/index.tsx
- frontend/src/pages/shop/KakaoLogin.tsx
- frontend/src/pages/shop/Login.tsx
- frontend/src/pages/shop/SocialSignup.tsx
- frontend/src/routes/RoutePath.tsx
- frontend/src/services/member.ts
Add Kakao Login Feature
- Make login for process first name when use kakao login feature.
- Add 2 pages for this.
> 🚀 FEAT: Add Kakao Login & change logic when kakao Login(firstname is null)

- frontend/src/components/menu/Menu.tsx
- frontend/src/lang/ko/AdminMenu.json
- frontend/src/routes/RoutePath.tsx
change name '요청' -> '금융' and it's submenus
- just change string values no route, .tsx files name
> Change menu names to clearly

- backend/abba/src/main/java/com/zon/abba/order/controller/OrderController.java
- backend/abba/src/main/java/com/zon/abba/order/entity/OrderDetail.java
- backend/abba/src/main/java/com/zon/abba/order/repository/OrderRepository.java
- backend/abba/src/main/java/com/zon/abba/order/request/RegisterOrderRequest.java
- backend/abba/src/main/java/com/zon/abba/order/service/OrderService.java
> 🚀 create order structure

- backend/abba/src/main/java/com/zon/abba/common/security/JwtAuthenticationFilter.java
> 🚀 update header token naming

- frontend/src/apis/mainApi.ts
- frontend/src/apis/productApi.ts
- frontend/src/components/index.tsx
- frontend/src/components/shop/search/SearchFilter.tsx
- frontend/src/components/shop/search/SearchProductList.tsx
- frontend/src/pages/shop/Search.tsx
- frontend/src/services/product.ts
- frontend/src/types/product.d.ts
develop Search Page
But not connect Api
> searchPage

- backend/abba/src/main/java/com/zon/abba/member/entity/Member.java
- backend/abba/src/main/java/com/zon/abba/member/service/SignupService.java
update in signup to add recommend
> 🚀 update in signup to add recommend

- backend/abba/src/main/java/com/zon/abba/cart/repository/CartRepository.java
- backend/abba/src/main/java/com/zon/abba/order/controller/OrderController.java
- backend/abba/src/main/java/com/zon/abba/order/request/RegisterCartOrderRequest.java
- backend/abba/src/main/java/com/zon/abba/order/service/OrderService.java
> 🚀 create order cart register api

- frontend/src/apis/memberApi.ts
- frontend/src/apis/sale.ts
- frontend/src/components/index.tsx
- frontend/src/components/shop/checkout/Address.tsx
- frontend/src/components/shop/checkout/AddressCard.tsx
- frontend/src/components/shop/checkout/Bill.tsx
- frontend/src/components/shop/checkout/Buyer.tsx
- frontend/src/components/shop/checkout/Delivery.tsx
- frontend/src/components/shop/checkout/Payment.tsx
- frontend/src/components/shop/checkout/Price.tsx
- frontend/src/components/shop/checkout/ProductList.tsx
- frontend/src/components/shop/checkout/SelectAddressModal.tsx
- frontend/src/components/shop/order/PageMove.tsx
- frontend/src/components/shop/order/SelectYear.tsx
- frontend/src/components/shop/order/ShopOrderCard.tsx
- frontend/src/components/shop/order/ShopOrderDetailCard.tsx
- frontend/src/components/shop/order/ShopOrderList.tsx
- frontend/src/components/shop/orderDetail/OrderInfo.tsx
- frontend/src/pages/shop/Checkout.tsx
- frontend/src/pages/shop/OrderDetail.tsx
- frontend/src/pages/shop/Orders.tsx
- frontend/src/routes/RoutePath.tsx
- frontend/src/services/sale.ts
- frontend/src/types/address.d.ts
- frontend/src/types/sale.d.ts
Develop checkout Page
Develop OrderPage
Do not Connect Apis
> checkout Page & OrderPage

- backend/abba/src/main/java/com/zon/abba/wishlist/controller/WishlistController.java
- backend/abba/src/main/java/com/zon/abba/wishlist/dto/WishlistDto.java
- backend/abba/src/main/java/com/zon/abba/wishlist/entity/Wishlist.java
- backend/abba/src/main/java/com/zon/abba/wishlist/mapping/WishListList.java
- backend/abba/src/main/java/com/zon/abba/wishlist/repository/WishlistRepository.java
- backend/abba/src/main/java/com/zon/abba/wishlist/request/RegisterWishlistRequest.java
- backend/abba/src/main/java/com/zon/abba/wishlist/request/WishlistIdRequest.java
- backend/abba/src/main/java/com/zon/abba/wishlist/service/WishlistService.java
> 🚀 create wishlist register, list, delete api

- backend/abba/src/main/java/com/zon/abba/account/entity/PointsHistory.java
- backend/abba/src/main/java/com/zon/abba/common/exception/OutOfStockException.java
- backend/abba/src/main/java/com/zon/abba/common/exception/handler/GlobalExceptionHandler.java
- backend/abba/src/main/java/com/zon/abba/common/exception/response/ErrorResponse.java
- backend/abba/src/main/java/com/zon/abba/order/request/RegisterCartOrderRequest.java
- backend/abba/src/main/java/com/zon/abba/order/request/RegisterOrderRequest.java
- backend/abba/src/main/java/com/zon/abba/order/response/ProductStockResponse.java
- backend/abba/src/main/java/com/zon/abba/order/service/OrderService.java
구매시 포인트 히스토리 등록 및 지갑 확인 후 금액 측정 등 로직 추가
> 🚀 update order logic

- frontend/src/components/shop/order/ShopOrderCard.tsx
- frontend/src/components/shop/order/ShopOrderDetailCard.tsx
- frontend/src/components/shop/orderDetail/OrderInfo.tsx
- frontend/src/components/shop/orderDetail/PaymentInfo.tsx
- frontend/src/components/shop/orderDetail/Recipient.tsx
- frontend/src/pages/shop/Mypage.tsx
Setting Shop Order Info
Develop Shop OrderDetailPage
> Setting Shop Order Info

- backend/abba/src/main/java/com/zon/abba/order/dto/MemberInfoDto.java
> 🚀 update member info dto

- frontend/src/apis/sale.ts
- frontend/src/components/admin/boardDetail/AdminBoardInfo.tsx
- frontend/src/components/admin/orderList/AdminOrderListCard.tsx
- frontend/src/components/shop/order/ShopOrderCard.tsx
- frontend/src/components/shop/orderDetail/OrderInfo.tsx
- frontend/src/components/shop/product/ProductCard.tsx
- frontend/src/pages/admin/AdminOrderList.tsx
- frontend/src/pages/shop/MypageOrders.tsx
- frontend/src/types/sale.d.ts
> MODIFY: Modify Fuctions About Order

- backend/abba/src/main/java/com/zon/abba/member/request/member/MemberInfoRequest.java
- backend/abba/src/main/java/com/zon/abba/member/service/MemberService.java
> 🚀 update member update removing password

- backend/abba/src/main/java/com/zon/abba/common/code/MailTitleCode.java
- backend/abba/src/main/java/com/zon/abba/member/controller/EmailController.java
- backend/abba/src/main/java/com/zon/abba/member/service/EmailService.java
- backend/abba/src/main/resources/templates/password.html
> 🚀 create password email api

- backend/abba/src/main/java/com/zon/abba/cart/repository/CartRepository.java
- backend/abba/src/main/java/com/zon/abba/cart/service/CartService.java
> 🚀 Add shopping cart duplicate removal logic

- backend/abba/src/main/java/com/zon/abba/account/repository/PointHoldingRepository.java
- backend/abba/src/main/java/com/zon/abba/account/service/PointService.java
- backend/abba/src/main/java/com/zon/abba/common/scheduler/SchedulerService.java
- backend/abba/src/main/java/com/zon/abba/commonCode/repository/CommonCodeRepository.java
- backend/abba/src/main/java/com/zon/abba/member/dto/ParentTreeDto.java
- backend/abba/src/main/java/com/zon/abba/member/mapping/ParentTree.java
- backend/abba/src/main/java/com/zon/abba/member/repository/RecommendedMemberRepository.java
- backend/abba/src/main/java/com/zon/abba/order/service/OrderService.java
> 🚀 Implementation of allowance distribution logic when purchasing goods

- backend/abba/src/main/java/com/zon/abba/order/controller/RefundController.java
- backend/abba/src/main/java/com/zon/abba/order/dto/RefundListDto.java
- backend/abba/src/main/java/com/zon/abba/order/mapping/RefundOrder.java
- backend/abba/src/main/java/com/zon/abba/order/repository/RefundRepository.java
> 🚀 Return list name changed to applicant account owner

- backend/abba/src/main/java/com/zon/abba/order/controller/RefundController.java
- backend/abba/src/main/java/com/zon/abba/order/entity/Refund.java
- backend/abba/src/main/java/com/zon/abba/order/mapping/RefundDetail.java
- backend/abba/src/main/java/com/zon/abba/order/repository/RefundRepository.java
- backend/abba/src/main/java/com/zon/abba/order/request/RefundIdRequest.java
- backend/abba/src/main/java/com/zon/abba/order/request/RegisterRefundRequest.java
- backend/abba/src/main/java/com/zon/abba/order/response/DetailRefundResponse.java
- backend/abba/src/main/java/com/zon/abba/order/service/RefundService.java
> 🚀 create refund detail api

- backend/abba/src/main/java/com/zon/abba/address/service/AddressService.java
bill address가 main address로 수정되던 버그 수정
> 🚀 fix set address error

- backend/abba/src/main/java/com/zon/abba/account/repository/PointsHistoryRepository.java
- backend/abba/src/main/java/com/zon/abba/account/service/PointService.java
- backend/abba/src/main/java/com/zon/abba/order/service/RefundService.java
> 🚀 Create a point refund process for refunds

- backend/abba/src/main/java/com/zon/abba/address/request/RegisterAddressRequest.java
> 🚀 fix typo

- backend/abba/src/main/java/com/zon/abba/account/entity/ChargeRefund.java
- backend/abba/src/main/java/com/zon/abba/account/repository/ChargeRefundRepository.java
- backend/abba/src/main/java/com/zon/abba/account/service/PointService.java
> 🚀 Create AK distribution logic when refunding

- backend/abba/src/main/java/com/zon/abba/account/dto/AccountDto.java
- backend/abba/src/main/java/com/zon/abba/account/entity/Accounts.java
- backend/abba/src/main/java/com/zon/abba/account/repository/AccountsRepository.java
- backend/abba/src/main/java/com/zon/abba/account/request/AccountRequest.java
- backend/abba/src/main/java/com/zon/abba/account/request/UpdateAccountRequest.java
- backend/abba/src/main/java/com/zon/abba/account/service/AccountService.java
- backend/abba/src/main/java/com/zon/abba/point/request/RefundRequest.java
- backend/abba/src/main/java/com/zon/abba/point/service/ChargeRefundService.java
> 🚀 Update main account registration and modification API

- backend/abba/src/main/java/com/zon/abba/member/controller/RecommendController.java
- backend/abba/src/main/java/com/zon/abba/member/dto/ParentTreeDto.java
- backend/abba/src/main/java/com/zon/abba/member/mapping/ParentTree.java
- backend/abba/src/main/java/com/zon/abba/member/repository/RecommendedMemberRepository.java
- backend/abba/src/main/java/com/zon/abba/member/service/RecommendService.java
- backend/abba/src/main/java/com/zon/abba/point/service/PointService.java
> 🚀 Create a recommender line list return API

- backend/abba/src/main/java/com/zon/abba/AbbaApplication.java
- backend/abba/src/main/java/com/zon/abba/common/redis/RedisService.java
- backend/abba/src/main/java/com/zon/abba/common/scheduler/SchedulerService.java
- backend/abba/src/main/java/com/zon/abba/point/controller/PointController.java
- backend/abba/src/main/java/com/zon/abba/point/response/ExchangeRateResponse.java
- backend/abba/src/main/java/com/zon/abba/point/service/ChargeRefundService.java
- backend/abba/src/main/java/com/zon/abba/point/service/ExchangeRateService.java
환율 체크 scheduler 추가
현재 KRW만 환율 받아옵니다.
받아온 환율은 redis에 저장 중이며 key는 국가코드입니다.
매일 자정에 스케줄링 돌도록 설정해놨으며 서버가 재가동되는 순간에도 스케줄링이 돕니다.
> 🚀 Add exchange rate check scheduler

- backend/abba/src/main/java/com/zon/abba/point/service/ChargeRefundService.java
- backend/abba/src/main/java/com/zon/abba/point/service/PointService.java
> 🚀 Completed implementation of point application processing logic

- frontend/src/apis/wallet.ts
- frontend/src/components/admin/historyDetail/AdminHistoryDetailCharge.tsx
- frontend/src/components/admin/historyDetail/AdminHistoryDetailOrder.tsx
- frontend/src/components/admin/historyDetail/AdminHistoryDetailPoint.tsx
- frontend/src/components/admin/historyDetail/AdminHistoryDetailTransfer.tsx
- frontend/src/components/index.tsx
- frontend/src/components/shop/historyDetail/HistoryDetailCharge.tsx
- frontend/src/components/shop/historyDetail/HistoryDetailOrder.tsx
- frontend/src/components/shop/historyDetail/HistoryDetailPoint.tsx
- frontend/src/components/shop/historyDetail/HistoryDetailTransfer.tsx
- frontend/src/components/shop/transiction/MyHistoryList.tsx
- frontend/src/components/shop/transiction/MyHistoryListCard.tsx
- frontend/src/pages/admin/AdminWalletDetail.tsx
- frontend/src/pages/admin/AdminWalletHistory.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/shop/Mypage/MyPageTransactionDetail.tsx
- frontend/src/pages/shop/Mypage/Mypage.tsx
- frontend/src/pages/shop/Mypage/MypageTransactions.tsx
- frontend/src/services/wallet.ts
- frontend/src/types/wallet.d.ts
Develop MyPage Transaction Page & Detail Page
> FEAT:Develop MyPage Transaction Page & Detail Page

- backend/abba/src/main/java/com/zon/abba/member/repository/SellerRepository.java
seller 이름 필터 종류 늘리기
1. firstName + " " + lastName
2. firstName + lastName
3. lastName + " " + firstName
4. lastName + firstName
> 🚀 update seller filter name

- backend/abba/src/main/java/com/zon/abba/member/controller/SellerController.java
- backend/abba/src/main/java/com/zon/abba/member/service/SellerService.java
- backend/abba/src/main/java/com/zon/abba/product/service/ProductService.java
product에서 sellerId가 잘못 등록되고 있던 부분 수정
> 🚀 update product add sellerId

- backend/abba/src/main/java/com/zon/abba/point/repository/ChargeRefundRepository.java
- backend/abba/src/main/java/com/zon/abba/point/service/ChargeRefundService.java
> 🚀 Add list return filter when charging refund

- backend/abba/src/main/java/com/zon/abba/common/redis/RedisConfig.java
- backend/abba/src/main/java/com/zon/abba/common/redis/RedisService.java
- backend/abba/src/main/java/com/zon/abba/point/dto/ChargeRefundListDto.java
- backend/abba/src/main/java/com/zon/abba/point/entity/ChargeRefund.java
- backend/abba/src/main/java/com/zon/abba/point/mapping/ChargeRefundInfo.java
- backend/abba/src/main/java/com/zon/abba/point/mapping/ChargeRefundList.java
- backend/abba/src/main/java/com/zon/abba/point/repository/ChargeRefundRepository.java
- backend/abba/src/main/java/com/zon/abba/point/request/ChargeRequest.java
- backend/abba/src/main/java/com/zon/abba/point/request/RefundRequest.java
- backend/abba/src/main/java/com/zon/abba/point/response/DetailChargeRefundResponse.java
- backend/abba/src/main/java/com/zon/abba/point/service/ChargeRefundService.java
- backend/abba/src/main/java/com/zon/abba/point/service/ExchangeRateService.java
- backend/abba/src/main/java/com/zon/abba/point/service/PointService.java
> 🚀 Modify exchange rate conversion logic

- backend/abba/src/main/java/com/zon/abba/product/controller/ProductController.java
- backend/abba/src/main/java/com/zon/abba/product/repository/ProductReviewRepository.java
- backend/abba/src/main/java/com/zon/abba/product/response/MyProductReviewResponse.java
- backend/abba/src/main/java/com/zon/abba/product/service/ProductService.java
- backend/abba/src/main/java/com/zon/abba/wishlist/repository/WishlistRepository.java
> 2025.02.14 productDetail에서 isWishtList Deleteyn 추가, 상품별 리뷰 리스트, 나의 리뷰 리스트 작업 완료

- frontend/src/apis/productApi.ts
- frontend/src/components/admin/reviewList/AdminReviewListComponent.tsx
- frontend/src/components/admin/reviewList/ProductList.tsx
- frontend/src/components/admin/reviewList/ProductListCard.tsx
- frontend/src/components/admin/reviewList/ReviewListCard.tsx
- frontend/src/components/index.tsx
- frontend/src/pages/admin/AdminReviewDetail.tsx
- frontend/src/pages/admin/AdminReviewList.tsx
- frontend/src/pages/index.tsx
- frontend/src/routes/RoutePath.tsx
- frontend/src/services/product.ts
Almost Done.
Review Detail Page Can not Work Because of Apis Problem.
> Develop Admin Product Review Pages
